name: resource_collect
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Nick Meinhold <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: any
  angular_components: any
  firebase: any
  firebase_dart_ui: any

dev_dependencies:
  sass_builder: any
  angular_test: any
  build_runner: any
  build_test: any
  build_web_compilers: '>=1.0.0 <2.0.0'
  test: any
